apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tokenization
  template:
    metadata:
      labels:
        app: tokenization
    spec:
      containers:
      - name: tokenization
        image: your-dockerhub-username/tokenization-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: DDB_TABLE_NAME
          value: "CardTokens"
        - name: PK_ALLOWED
          value: "pk_test_123456"
---
apiVersion: v1
kind: Service
metadata:
  name: tokenization-service
spec:
  type: LoadBalancer
  selector:
    app: tokenization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000