apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tokenization-service
  template:
    metadata:
      labels:
        app: tokenization-service
    spec:
      containers:
        - name: tokenization-service
          image: 423469511259.dkr.ecr.us-east-1.amazonaws.com/tokenization-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DYNAMODB_TABLE
              value: "CardTokens"
---
apiVersion: v1
kind: Service
metadata:
  name: tokenization-service
spec:
  selector:
    app: tokenization-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer